### ISSUE TITLE
wrong syntax validation

### ISSUE THREAD

**Issue by JonRC** [philosowaffle/vs-openapi-designer#38]
This syntax below is incorrect but it isn't detected by syntax validator.
```
type: object
properties:
  exampleField:
    type: boolean
  secondExampleField:
    type: array   ----------------> It is wrong. It needs "items"
  otherField:
    type: string
```
